language: bash

sudo: false

env:
  global:
    - REPO=drtrigon/docker-arduino DOCKERTAG=ubuntu-14.04  # ARDUINO_VERSION=1.8.2
  matrix:
    #- BOARD="arduino:avr:uno"
    - BOARD="arduino:avr:nano:cpu=atmega328"

services:
  - docker

install:
  - docker pull $REPO:$DOCKERTAG ;

script:
  - docker images ;
  - docker run -t -d --name testing $REPO:$DOCKERTAG bin/bash ;
  - docker ps -l ;
  - docker exec -t testing  apt-get update ;
  - docker exec -t testing  apt-get install -y git binutils tree ;
  - docker exec -t testing  git clone https://github.com/drtrigon/sketchbook.git ;
  - docker exec -t testing  arduino --verify --board $BOARD --verbose --preserve-temp-files sketchbook/MultiWii_2_4/MultiWii/MultiWii.ino ;
  # Output post-verify info
  - docker exec -t testing  /bin/bash -c 'export ELF_FILE=`find /tmp/ -name "MultiWii.ino.elf"`; readelf -a $ELF_FILE' ;
  - docker exec -t testing  /bin/bash -c 'export ELF_FILE=`find /tmp/ -name "MultiWii.ino.elf"`; strings -d $ELF_FILE' ;
  - docker exec -t testing  /bin/bash -c 'export ELF_FILE=`find /tmp/ -name "MultiWii.ino.elf"`; size $ELF_FILE' ;
  - docker exec -t testing  tree ;
  - docker stop testing ;
  - docker rm testing ;
  #- docker rmi $REPO:$DOCKERTAG
  #- docker images ;
  #- docker container ls ;
  - docker ps -l ;

notifications:
  email: false
